version: "3.9"

services:
  glpi-voice-bot:
    build: .
    container_name: glpi-voice-bot
    restart: unless-stopped
    env_file:
      - .env
    volumes:
      - ./transcripciones:/app/transcripciones
    environment:
      - PYTHONUNBUFFERED=1
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"
